name: Build

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Source Checkout
        uses: actions/checkout@v2

      - name: Build
        run: echo "Source code build"

      - name: Test
        run: echo "Run test code"

      - run: echo hello > world.txt

      - name: Upload Api Specs Artifact
        id: upload_api_specs_artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello.pr-${{ github.event.number }}.txt
          path: world.txt

      - name: Create PR Comment
        uses: actions/github-script@v7
        env:
          PR_NO: "2"
          URL: ${{ steps.upload_api_specs_artifact.outputs.artifact-url }}
        with:
          script: |
            console.log(context)
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `The api specs address for pull request ${context.payload.pull_request.number}~~~~
              ${{env.URL}}:newspaper_roll:`
            })
            
