name: Deploy development

on:
  pull_request:
    types: [ labeled ]

jobs:
  deploy:
    if: ${{ github.event.label.name == 'deploy development' }}
    env: development
    runs-on: ubuntu-latest
    steps:
      - name: Source Checkout
        uses: actions/checkout@v2

      - name: Generate Version
        id: generate_version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "v${major}.${minor}.${patch}-pr${{ github.event.number }}"

      - name: Package
        env:
          CONTAINER_TAG: ${{ steps.generate_version.outputs.version }}
        run: echo "Container image [$CONTAINER_TAG] push to ECR [cso-dev]"

      - name: Deploy
        env:
          CONTAINER_TAG: ${{ steps.generate_version.outputs.version }}
          ENV_CONTEXT: ${{ toJSON(env) }}
        run: echo $ENV_CONTEXT
