name: Deploy development

on:
  pull_request:
    types: [ labeled ]

jobs:
  deploy:
    if: ${{ github.event.label.name == 'deploy development' }}
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Source Checkout
        uses: actions/checkout@v2

      - name: Generate Version
        id: generate_version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          branch: "HEAD"
          tag_prefix: "v"
          format: "v${major}.${minor}.${patch}-pr${{ github.event.number }}"

      - name: Package
        env:
          CONTAINER_TAG: ${{ steps.generate_version.outputs.version }}
        run: echo "Push Container image [$CONTAINER_TAG] to ECR [cso-dev]"

      - name: Deploy
        env:
          CONTAINER_TAG: ${{ steps.generate_version.outputs.version }}
        run: echo "Deploy container image [$CONTAINER_TAG] to development environment"
