name: Deploy development

on:
  pull_request:
    types: [ labeled ]

jobs:
  deploy:
    if: ${{ github.event.label.name == 'deploy development' }}
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Source Checkout
        uses: actions/checkout@v4
      
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

      - name: Generate Container Tag
        run: |
          COMMIT_SHA=${{ github.sha }}
          echo "CONTAINER_TAG=pr${{ github.event.number }}-${COMMIT_SHA:0:7}" >> $GITHUB_ENV

      - name: Package
        run: echo "Push Container image ${{ env.CONTAINER_TAG }} to ECR [cso-dev]"

      - name: Deploy
        run: echo "Deploy container image ${{ env.CONTAINER_TAG }} to development environment"
