name: Deploy staging

on:
  pull_request:
    types: [ closed ]

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Source Checkout
        uses: actions/checkout@v2

      - name: Generate Version
        id: generate_version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "v${major}.${minor}.${patch}-${increment}"
      
      - name: Build
        run: echo "Source code build"
      
      - name: Test
        run: echo "Run test code"
        
      - name: Package
        env:
          GITHUB_CONTAINER_TAG: ${{ steps.generate_version.outputs.version }}
          ECR_CONTAINER_TAG: ${{ steps.generate_version.outputs.version }}
        run: |
          echo "Container image [$GITHUB_CONTAINER_TAG] push to GitHub package"; \
          echo "Copy container image [$ECR_CONTAINER_TAG] to ECR [cso-stg]"

      - name: Deploy
        env:
          CONTAINER_TAG: ${{ steps.generate_version.outputs.version }}
        run: echo "Deploy container image [$CONTAINER_TAG]"
