name: Deploy staging

on:
  push:
    branches:
      - main
  pull_request:
    types: [ closed ]

jobs:
  deploy:
    if: ${{ github.event.push || github.event.pull_request.merged == true }}
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Source Checkout
        uses: actions/checkout@v2

      - name: Generate Container Tag
        run: |
          COMMIT_HASH_SHORT=$(git rev-parse --short HEAD)
          echo "CONTAINER_TAG=sha-$COMMIT_HASH_SHORT" >> $GITHUB_ENV

      - name: Build
        run: echo "Source code build"

      - name: Test
        run: echo "Run test code"

      - name: Package
        run: |
          echo "Push Container image [${{ env.CONTAINER_TAG }}] to GitHub package"; \
          echo "Copy container image [${{ env.CONTAINER_TAG }}] to ECR [cso-stg]"

      - name: Deploy
        run: echo "Deploy container image [${{ env.CONTAINER_TAG }}] to staging environment"
