name: Deploy development

on:
  pull_request:
    types: [ labeled ]

jobs:
  deploy:
    if: ${{ github.event.label.name == 'deploy development' }}
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Source Checkout
        uses: actions/checkout@v2

      - name: Generate Commit SHA
        run: echo "COMMIT_HASH_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Package
        env:
          CONTAINER_TAG: pr${{ github.event.number }}-${{ env.COMMIT_HASH_SHORT }}
        run: echo "Push Container image [$CONTAINER_TAG] to ECR [cso-dev]"

      - name: Deploy
        env:
          CONTAINER_TAG: pr${{ github.event.number }}-${{ env.COMMIT_HASH_SHORT }}
        run: echo "Deploy container image [$CONTAINER_TAG] to development environment"
