name: Deploy development

on:
  pull_request:
    types: [ labeled ]

jobs:
  deploy:
    if: ${{ github.event.label.name == 'deploy development' }}
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Source Checkout
        uses: actions/checkout@v2

      - name: Generate Container Tag
        run: |
          echo "COMMIT_HASH_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "CONTAINER_TAG=pr${{ github.event.number }}-${{ env.COMMIT_HASH_SHORT }}" >> $GITHUB_ENV

      - name: Package
        run: echo "Push Container image ${{ env.CONTAINER_TAG }} to ECR [cso-dev]"

      - name: Deploy
        run: echo "Deploy container image ${{ env.CONTAINER_TAG }} to development environment"
