name: workflow dispatch sample

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy Environment'
        required: true
        default: 'STG'
        type: choice
        options:
        - STG
        - PRD

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - env:
          ENVIRONMENT: ${{ inputs.environment }}
        id: generate_container_env
        run: |
          echo "Environment: $ENVIRONMENT"
          echo "container_tag=${{ github.ref_name }}-$(date '+%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      - env:
          CONTAINER_TAG: ${{ steps.generate_container_env.outputs.container_tag }}
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "Container Tag: $CONTAINER_TAG"
          echo "Environment: ${ENVIRONMENT,,}"

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
