name: workflow dispatch sample

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy Environment'
        required: true
        default: 'STG'
        type: choice
        options:
        - STG
        - PRD
      tag:
        description: 'Deploy tag (ex. 2025.01.001)'
        required: false

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - id: generate_container_env_test
        env:
          INPUT_TAG: ${{ inputs.tag }}
        run: |
          if [ -z "$INPUT_TAG" ]
          then
            echo "container_tag=${{ github.event.ref }}-$(date '+%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"
          else
            echo "container_tag=$INPUT_TAG" >> "$GITHUB_OUTPUT"
          fi

      - run: |
          echo ${{ steps.generate_container_env_test.outputs.container_tag }}
        
      - run: |
          docker --version
          
      - env:
          ENVIRONMENT: ${{ inputs.environment }}
        id: generate_container_env
        run: |
          echo "Environment: $ENVIRONMENT"
          echo "container_tag=${{ github.ref_name }}-$(date '+%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      - env:
          CONTAINER_TAG: ${{ steps.generate_container_env.outputs.container_tag }}
          ENVIRONMENT: ${{ inputs.environment }}
          REF_BRANCH: feat/test
        run: |
          echo "Container Tag: $CONTAINER_TAG"
          echo "Environment: ${ENVIRONMENT,,}"
          echo "RefBranch: ${REF_BRANCH/\//-}"

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
