name: gcp test

on: workflow_dispatch

jobs:
  gcp-test:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Run gcloud Command'
      run: 'gcloud compute ssh abc-imgai-test --zonbe=us-west1-a --command="echo Hello world"'
