name: github event test

on:
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'closed'

jobs:
  always:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

  not_closed:
    if: ${{ github.event.pull_request.type != 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo 'not closed pull request type'

  not_closed_and_not_draft:
    if: ${{ github.event.pull_request.type != 'closed' && github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo 'not closed and not draft pull request type'

  merged_to_main:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo 'merged to main'
