name: File send efs throught s3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
